name: maker_exampapers
description: "تطبيق مستقل لتوليد أوراق اختبارات الطلاب"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # المكتبات الأساسية للمشروع المحدث
  excel: ^4.0.0
  pdf: ^3.10.8
  file_picker: ^8.0.0 # ✅ تم التحديث لحل تحذيرات المنصات في السجلات
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1
  google_mlkit_text_recognition: ^0.13.0
  shared_preferences: ^2.2.3
  qrscan_plus: ^1.0.8

  # أضف هذه الحزمة هنا
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # حزم ملف الخط بالاسم والامتداد الصحيح تماماً
  assets:
    - assets/fonts/Amiri_Regular.ttf

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri_Regular.ttf
